# Generated by Django 4.2.19 on 2025-04-07 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Prénom', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=50)),
                ('NIN', models.CharField(max_length=20, unique=True)),
                ('matricule', models.CharField(max_length=12, null=True, unique=True)),
                ('dat_naiss', models.DateField()),
                ('Lieu_naiss', models.CharField(max_length=100)),
                ('date_recrut', models.DateField()),
                ('grade', models.CharField(choices=[('محاضر أ', 'محاضر أ'), ('محاضر ب', 'محاضر ب'), ('مساعد أ', 'مساعد أ'), ('مساعد ب', 'مساعد ب'), ('مساعد إستشفائي', 'مساعد إستشفائي'), ('محاضر إستشفائي أ', 'محاضر إستشفائي أ'), ('محاضر إستشفائي ب', 'محاضر إستشفائي ب'), ('أستاذ', 'أستاذ'), ('أستاذ متميز', 'أستاذ متميز')], max_length=200)),
                ('Echelon', models.CharField(max_length=20)),
                ('date_grade', models.DateField()),
                ('Catégorie', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('في الخدمة', 'في الخدمة'), ('وضع تحت التصرف جمعوي', 'وضع تحت التصرف جمعوي'), ('وضع تحت التصرف بيداغوجي', 'وضع تحت التصرف بيداغوجي'), ('عطلة مرضية طويلة المدة', 'عطلة مرضية طويلة المدة'), ('إنتداب محدد', 'إنتداب محدد'), ('إنتداب غ محدد', 'إنتداب غ محدد'), ('إستيداع شخصي', 'إستيداع شخصي'), ('إستيداع قانوني', 'إستيداع قانوني')], default='في الخدمة', max_length=30)),
                ('faculte', models.CharField(choices=[('الرياضة', 'الرياضة'), ('كلية الطب', 'كلية الطب'), ('الطبيعة والحياة', 'الطبيعة والحياة'), ('الرياضيات وعلوم المادة', 'الرياضيات وعلوم المادة'), ('معهد التكنولوجيا', 'معهد التكنولوجيا'), ('الإقتصاد', 'الإقتصاد'), ('اللغات', 'اللغات'), ('العلوم الإنسانية', 'العلوم الإنسانية'), ('الحقوق و العلوم السياسية', 'الحقوق و العلوم السياسية'), ('التكنولوجيات الحديثة', 'التكنولوجيات الحديثة'), ('العلوم التطبيقية', 'العلوم التطبيقية'), ('المحروقات', 'المحروقات')], max_length=200)),
                ('debut_position', models.DateField(blank=True, null=True)),
                ('fin_position', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDF_employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/employe/', verbose_name='الملفات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('n_ident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employe_pdfs', to='employe.employe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_empl_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
