# Generated by Django 4.2.19 on 2025-04-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_grade',
            field=models.DateField(null=True),
        ),
    ]
