# Generated by Django 4.2.19 on 2025-04-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0002_alter_employe_date_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='dat_naiss',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_recrut',
            field=models.DateField(blank=True),
        ),
    ]
