# Generated by Django 4.2.19 on 2025-04-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0003_alter_employe_dat_naiss_alter_employe_date_recrut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_recrut',
            field=models.DateField(null=True),
        ),
    ]
