# Generated by Django 4.2.19 on 2025-04-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0004_alter_employe_date_recrut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='debut_position',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='fin_position',
        ),
    ]
