# Generated by Django 4.2.19 on 2025-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0005_remove_employe_debut_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='debut_position',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='fin_position',
            field=models.DateField(blank=True, null=True),
        ),
    ]
