# Generated by Django 4.2.19 on 2025-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0007_alter_employe_faculte_alter_employe_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_employe',
            name='pdf_file',
            field=models.FileField(upload_to='employe/', verbose_name='الملفات'),
        ),
    ]
