# Generated by Django 4.2.19 on 2025-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0008_alter_pdf_employe_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='date_grade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
