# Generated by Django 4.2.19 on 2025-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0009_alter_employe_date_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf_employe',
            name='grade',
            field=models.CharField(default='', max_length=100),
        ),
    ]
