# Generated by Django 4.2.19 on 2025-04-14 08:41

from django.db import migrations, models
import employe.models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0010_pdf_employe_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_employe',
            name='pdf_file',
            field=models.FileField(upload_to=employe.models.upload_to, verbose_name='الملفات'),
        ),
    ]
