# Generated by Django 4.2.19 on 2025-03-19 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Prénom', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=50)),
                ('NIN', models.CharField(max_length=20, unique=True)),
                ('matricule', models.CharField(max_length=12, null=True, unique=True)),
                ('dat_naiss', models.DateField()),
                ('Lieu_naiss', models.CharField(max_length=200)),
                ('date_recrut', models.DateField()),
                ('grade', models.CharField(choices=[('محاضر أ', 'محاضر أ'), ('محاضر ب', 'محاضر ب'), ('مساعد أ', 'مساعد أ'), ('مساعد ب', 'مساعد ب'), ('أستاذ', 'أستاذ')], max_length=200)),
                ('Echelon', models.CharField(max_length=20)),
                ('Catégorie', models.CharField(max_length=5)),
                ('position', models.CharField(choices=[('En poste', 'En poste'), ('Congé maladie longue durée', 'Congé maladie longue durée'), ('Congé maternité', 'Congé maternité'), ('Mise en dispoistion', 'Mise en dispoistion'), ('Détachement', 'Détachement')], default='en poste', max_length=30)),
                ('faculte', models.CharField(choices=[('الرياضة', 'الرياضة'), ('الطب', 'الطب'), ('الطبيعة والحياة', 'الطبيعة والحياة'), ('الرياضيات وعلوم المادة', 'الرياضيات وعلوم المادة'), ('معهد التكنولوجيا', 'معهد التكنولوجيا'), ('الإقتصاد', 'الإقتصاد'), ('اللغات', 'اللغات'), ('العلوم الإنسانية', 'العلوم الإنسانية'), ('الحقوق و العلوم السياسية', 'الحقوق و العلوم السياسية'), ('التكنولوجيات الحديثة', 'التكنولوجيات الحديثة'), ('العلوم التطبيقية', 'العلوم التطبيقية'), ('المحروقات', 'المحروقات')], max_length=200)),
                ('debut_mis_dispo', models.DateField(blank=True, null=True)),
                ('fin_mis_dispo', models.DateField(blank=True, null=True)),
                ('debut_detatch', models.DateField(blank=True, null=True)),
                ('fin_detach', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/enseig/', verbose_name='الملفات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('n_ident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseign_pdfs', to='enseignants.enseignant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseign_pdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
