# Generated by Django 4.2.19 on 2025-03-19 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PDFFile',
            new_name='PDF_enseign',
        ),
    ]
