# Generated by Django 4.2.19 on 2025-03-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0002_rename_pdffile_pdf_enseign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
