# Generated by Django 4.2.19 on 2025-03-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0003_alter_enseignant_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='matricule',
        ),
    ]
