# Generated by Django 4.2.19 on 2025-03-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0004_remove_enseignant_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
