# Generated by Django 4.2.19 on 2025-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0006_alter_enseignant_catégorie_alter_enseignant_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='debut_detatch',
            new_name='debut_detach',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='position',
            field=models.CharField(choices=[('En poste', 'En poste'), ('Congé maladie longue durée', 'Congé maladie longue durée'), ('Congé maternité', 'Congé maternité'), ('Mise en disponibilité', 'Mise en disponibilité'), ('Détachement', 'Détachement')], default='في الخدمة', max_length=30),
        ),
    ]
