# Generated by Django 4.2.19 on 2025-03-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0007_rename_debut_detatch_enseignant_debut_detach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='faculte',
            field=models.CharField(choices=[('الرياضة', 'الرياضة'), ('كلية الطب', 'كلية الطب'), ('الطبيعة والحياة', 'الطبيعة والحياة'), ('الرياضيات وعلوم المادة', 'الرياضيات وعلوم المادة'), ('معهد التكنولوجيا', 'معهد التكنولوجيا'), ('الإقتصاد', 'الإقتصاد'), ('اللغات', 'اللغات'), ('العلوم الإنسانية', 'العلوم الإنسانية'), ('الحقوق و العلوم السياسية', 'الحقوق و العلوم السياسية'), ('التكنولوجيات الحديثة', 'التكنولوجيات الحديثة'), ('العلوم التطبيقية', 'العلوم التطبيقية'), ('المحروقات', 'المحروقات')], max_length=200),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('محاضر أ', 'محاضر أ'), ('محاضر ب', 'محاضر ب'), ('مساعد أ', 'مساعد أ'), ('مساعد ب', 'مساعد ب'), ('مساعد إستشفائي', 'مساعد إستشفائي'), ('محاضر إستشفائي أ', 'محاضر إستشفائي أ'), ('محاضر إستشفائي ب', 'محاضر إستشفائي ب'), ('أستاذ', 'أستاذ'), ('أستاذ متميز', 'أستاذ متميز')], max_length=200),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='position',
            field=models.CharField(choices=[('في الخدمة', 'في الخدمة'), ('وضع تحت التصرف', 'وضع تحت التصرف'), ('عطلة مرضية طويلة المدة', 'عطلة مرضية طويلة المدة'), ('إنتداب', 'إنتداب'), ('إستيداع', 'إستيداع')], default='في الخدمة', max_length=30),
        ),
    ]
