# Generated by Django 4.2.19 on 2025-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0008_alter_enseignant_faculte_alter_enseignant_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='debut_detach',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='debut_mis_dispo',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='fin_detach',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='fin_mis_dispo',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='debut_position',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='fin_position',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='position',
            field=models.CharField(choices=[('في الخدمة', 'في الخدمة'), ('وضع تحت التصرف جمعوي', 'وضع تحت التصرف جمعوي'), ('وضع تحت التصرف بيداغوجي', 'وضع تحت التصرف بيداغوجي'), ('عطلة مرضية طويلة المدة', 'عطلة مرضية طويلة المدة'), ('إنتداب محدد', 'إنتداب محدد'), ('إنتداب غ محدد', 'إنتداب غ محدد'), ('إستيداع شخصي', 'إستيداع شخصي'), ('إستيداع قانوني', 'إستيداع قانوني')], default='في الخدمة', max_length=30),
        ),
    ]
