# Generated by Django 4.2.19 on 2025-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0009_remove_enseignant_debut_detach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Lieu_naiss',
            field=models.CharField(max_length=100),
        ),
    ]
