# Generated by Django 4.2.19 on 2025-04-09 19:35

from django.db import migrations, models
import enseignants.models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0011_pdf_enseign_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='date_grade',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pdf_enseign',
            name='pdf_file',
            field=models.FileField(upload_to=enseignants.models.upload_to, verbose_name='الملفات'),
        ),
    ]
