# Generated by Django 4.2.19 on 2025-04-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0013_alter_enseignant_date_grade_alter_enseignant_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('محاضر أ', 'محاضر أ'), ('محاضر ب', 'محاضر ب'), ('مساعد أ', 'مساعد أ'), ('مساعد ب', 'مساعد ب'), ('مساعد', 'مساعد'), ('مساعد إستشفائي', 'مساعد إستشفائي'), ('محاضر إستشفائي أ', 'محاضر إستشفائي أ'), ('محاضر إستشفائي ب', 'محاضر إستشفائي ب'), ('أستاذ', 'أستاذ'), ('أستاذ مميز', 'أستاذ مميز'), ('Assistant', 'Assistant')], max_length=200),
        ),
        migrations.AlterField(
            model_name='pdf_enseign',
            name='grade',
            field=models.CharField(choices=[('محاضر أ', 'محاضر أ'), ('محاضر ب', 'محاضر ب'), ('مساعد أ', 'مساعد أ'), ('مساعد ب', 'مساعد ب'), ('مساعد', 'مساعد'), ('مساعد إستشفائي', 'مساعد إستشفائي'), ('محاضر إستشفائي أ', 'محاضر إستشفائي أ'), ('محاضر إستشفائي ب', 'محاضر إستشفائي ب'), ('أستاذ', 'أستاذ'), ('أستاذ متميز', 'أستاذ متميز'), ('Assistant', 'Assistant')], default='Grad', max_length=60),
        ),
    ]
