# Generated by Django 4.2.19 on 2025-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0014_alter_enseignant_grade_alter_pdf_enseign_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_enseign',
            name='grade',
            field=models.CharField(choices=[('أستاذ محاضر قسم أ', 'أستاذ محاضر قسم أ'), ('أستاذ محاضر قسم ب', 'أستاذ محاضر قسم ب'), ('أستاذ مساعد قسم أ', 'أستاذ مساعد قسم أ'), ('أستاذ مساعد قسم ب', 'أستاذ مساعد قسم ب'), ('أستاذ مساعد', 'أستاذ مساعد'), ('أستاذ مساعد إستشفائي جامعي', 'أستاذ مساعد إستشفائي جامعي'), ('أستاذ إستشفائي جامعي', 'أستاذ إستشفائي جامعي'), ('أستاذ محاضر إستشفائي جامعي أ', 'أستاذ محاضر إستشفائي جامعي أ'), ('أستاذ محاضر إستشفائي جامعي ب', 'أستاذ محاضر إستشفائي جامعي ب'), ('أستاذ', 'أستاذ'), ('أستاذ متميز', 'أستاذ متميز'), ('معيد', 'معيد')], default='Grad', max_length=60),
        ),
    ]
