# Generated by Django 4.2.19 on 2025-02-28 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=200)),
                ('Prénom', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=50)),
                ('NIN', models.CharField(max_length=20)),
                ('dat_naiss', models.DateField()),
                ('Lieu_naiss', models.CharField(max_length=200)),
                ('date_recrut', models.DateField()),
                ('grade', models.CharField(max_length=200)),
                ('Catégorie', models.CharField(max_length=5)),
                ('position', models.CharField(max_length=20)),
                ('faculte', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='fac',
        ),
        migrations.RemoveField(
            model_name='pdffile',
            name='name',
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/contart/'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='n_ident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contrat_pdfs', to='posts.emp_contrat'),
            preserve_default=False,
        ),
    ]
