# Generated by Django 4.2.19 on 2025-03-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_emp_contrat_remove_pdffile_fac_remove_pdffile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='grad',
            field=models.CharField(choices=[('أستاذ', 'أستاذ'), ('مساعد أ', 'مساعد أ')], default='', max_length=50),
        ),
    ]
