# Generated by Django 4.2.19 on 2025-03-05 22:35

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_pdffile_grad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='grad',
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to=posts.models.upload_to),
        ),
    ]
