# Generated by Django 4.2.19 on 2025-03-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_pdffile_grad_alter_pdffile_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
