# Generated by Django 4.2.19 on 2025-03-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_pdffile_pdf_file_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_contrat',
            name='matricule',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='emp_contrat',
            name='NIN',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
