# Generated by Django 4.2.19 on 2025-03-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_emp_contrat_matricule_alter_emp_contrat_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_contrat',
            name='faculte',
            field=models.CharField(choices=[('كلية العلوم الإنسانية', 'كلية العلوم الإنسانية'), ('كلية العلوم الإقتصادية', 'كلية العلوم الإقتصادية')], max_length=200),
        ),
        migrations.AlterField(
            model_name='emp_contrat',
            name='position',
            field=models.CharField(choices=[('en poste', 'en poste'), ('Congé maladie longue durée', 'Congé maladie longue durée'), ('Mise en disponibilité', 'Mise en disponibilité')], default='في الخدمة', max_length=30),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/contrat/', verbose_name='الملفات'),
        ),
    ]
