# Generated by Django 4.2.19 on 2025-03-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_emp_contrat_faculte_alter_emp_contrat_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_contrat',
            name='debut_mis_dispo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emp_contrat',
            name='fin_mis_dispo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_contrat',
            name='faculte',
            field=models.CharField(choices=[('المديرية', 'المديرية'), ('الرياضة', 'الرياضة'), ('الطب', 'الطب'), ('الطبيعة والحياة', 'الطبيعة والحياة'), ('الرياضيات وعلوم المادة', 'الرياضيات وعلوم المادة'), ('معهد التكنولوجيا', 'معهد التكنولوجيا'), ('الإقتصاد', 'الإقتصاد'), ('اللغات', 'اللغات'), ('العلوم الإنسانية', 'العلوم الإنسانية'), ('الحقوق و العلوم السياسية', 'الحقوق و العلوم السياسية'), ('التكنولوجيات الحديثة', 'التكنولوجيات الحديثة'), ('العلوم التطبيقية', 'العلوم التطبيقية'), ('المحروقات', 'المحروقات')], max_length=200),
        ),
    ]
