# Generated by Django 4.2.19 on 2025-03-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_emp_contrat_debut_mis_dispo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_contrat',
            name='faculte',
            field=models.CharField(choices=[('المديرية', 'المديرية'), ('الرياضة', 'الرياضة'), ('كلية الطب', 'كلية الطب'), ('الطبيعة والحياة', 'الطبيعة والحياة'), ('الرياضيات وعلوم المادة', 'الرياضيات وعلوم المادة'), ('معهد التكنولوجيا', 'معهد التكنولوجيا'), ('الإقتصاد', 'الإقتصاد'), ('اللغات', 'اللغات'), ('العلوم الإنسانية', 'العلوم الإنسانية'), ('الحقوق و العلوم السياسية', 'الحقوق و العلوم السياسية'), ('التكنولوجيات الحديثة', 'التكنولوجيات الحديثة'), ('العلوم التطبيقية', 'العلوم التطبيقية'), ('المحروقات', 'المحروقات')], max_length=200),
        ),
        migrations.AlterField(
            model_name='emp_contrat',
            name='position',
            field=models.CharField(choices=[('في الخدمة', 'في الخدمة'), ('عطلة مرضية طويلة المدة', 'عطلة مرضية طويلة المدة'), ('إستيداع', 'إستيداع')], default='في الخدمة', max_length=30),
        ),
    ]
