# Generated by Django 4.2.19 on 2025-03-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_emp_contrat_faculte_alter_emp_contrat_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_contrat',
            name='grade',
            field=models.CharField(choices=[('عامل مهني من المستوى الأول', 'عامل مهني من المستوى الأول'), ('عامل مهني من المستوى الأول ت ج', 'عامل مهني من المستوى الأول ت ج'), ('حارس', 'حارس'), ('عامل مهني من المستوى الثاني', 'عامل مهني من المستوى الثاني'), ('عون وقاية من المستوى الأول', 'عون وقاية من المستوى الأول'), ('سائق سيارة من المستوى الأول', 'سائق سيارة من المستوى الأول'), ('عامل مهني من المستوى الثالث', 'عامل مهني من المستوى الثالث'), ('عون خدمات من المستوى الثالث', 'عون خدمات من المستوى الثالث')], max_length=200),
        ),
    ]
