# Generated by Django 4.2.19 on 2025-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_emp_contrat_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_contrat',
            name='position',
            field=models.CharField(choices=[('في الخدمة', 'في الخدمة'), ('عطلة مرضية طويلة المدة', 'عطلة مرضية طويلة المدة'), ('إستيداع', 'إستيداع'), ('إنتداب', 'إنتداب')], default='في الخدمة', max_length=30),
        ),
    ]
