# Generated by Django 4.2.19 on 2025-03-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_emp_contrat_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_contrat',
            old_name='debut_mis_dispo',
            new_name='debut_position',
        ),
        migrations.RenameField(
            model_name='emp_contrat',
            old_name='fin_mis_dispo',
            new_name='fin_position',
        ),
    ]
