# Generated by Django 4.2.19 on 2025-04-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_rename_debut_mis_dispo_emp_contrat_debut_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_contrat',
            name='position',
            field=models.CharField(choices=[('في الخدمة', 'في الخدمة'), ('عطلة مرضية طويلة المدة', 'عطلة مرضية طويلة المدة'), ('عطلة غ مدفوعة الأجر', 'عطلة غ مدفوعة الأجر'), ('إنتداب', 'إنتداب')], default='في الخدمة', max_length=30),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='pdf_file',
            field=models.FileField(upload_to='contrat/', verbose_name='الملفات'),
        ),
    ]
